version: "3.8"

x-docmost-common: &docmost-common
  image: docmost/docmost:0.5.0
  restart: unless-stopped
  environment:
    - DB_HOST=postgres
    - REDIS_HOST=redis
  depends_on:
    - postgres
    - redis
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
    interval: 30s
    timeout: 10s
    retries: 3

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - docmost1
      - docmost2
      - docmost3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  docmost1:
    <<: *docmost-common
    hostname: docmost1

  docmost2:
    <<: *docmost-common
    hostname: docmost2

  docmost3:
    <<: *docmost-common
    hostname: docmost3

  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=docmost
      - POSTGRES_PASSWORD=securepassword
      - POSTGRES_DB=docmost
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docmost"]
      interval: 30s
      timeout: 5s
      retries: 3

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
  redis_data:
