---
- name: Ensure systemd is reloaded
  systemd:
    daemon_reload: yes

- name: Start and enable Docmost service
  systemd:
    name: docmost
    state: started
    enabled: yes
    daemon_reload: yes

- name: Add service status check
  command: systemctl is-active docmost
  register: service_status
  changed_when: false
  failed_when: service_status.rc != 0
  check_mode: no
